ALTER TABLE public.users 
ADD COLUMN IF NOT EXISTS name VARCHAR(255),
ADD COLUMN IF NOT EXISTS phone VARCHAR(20),
ADD COLUMN IF NOT EXISTS address TEXT;

UPDATE public.users SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL;
